using Rhino.UI;

namespace Rhino.AI.WebPanel;

// The panel is TypeScript in a webview, which Rhino's string extractor cannot read, so its English lives here.
internal static class PanelStrings
{
    public static IReadOnlyDictionary<string, string> Localized() => new Dictionary<string, string>
    {
        ["header.switchAgent"] = LOC.STR("Switch agent"),
        ["header.noAgent"] = LOC.STR("No agent"),
        ["header.nothingConfigured"] = LOC.STR("nothing configured"),
        ["header.history"] = LOC.STR("Conversation history"),
        ["header.newConversation"] = LOC.STR("New conversation  (Ctrl+Shift+N)"),
        ["header.settings"] = LOC.STR("AI settings"),

        ["empty.ready"] = LOC.STR("{0} is ready"),
        ["empty.theAgent"] = LOC.STR("The agent"),
        ["empty.body"] = LOC.STR("It can read the document, run scripts, drive Grasshopper and capture views. Mention @context to point it at something specific."),
        ["empty.starterCommand"] = LOC.STR("Create a command that generates 100 random spheres"),
        ["empty.starterTower"] = LOC.STR("Build a twisty tower in Grasshopper"),
        ["empty.starterLayers"] = LOC.STR("Organize the objects in the active viewport into layers"),
        ["empty.noAgent"] = LOC.STR("No agent available"),
        ["empty.noAgentBody"] = LOC.STR("Install Claude Code, Codex or Gemini CLI and sign in, then pick it here."),
        ["empty.openSettings"] = LOC.STR("Open AI settings"),
        ["empty.setupGuide"] = LOC.STR("Read the setup guide"),

        ["plan.head"] = LOC.STR("Plan"),
        ["turn.copy"] = LOC.STR("Copy the reply"),
        ["turn.retry"] = LOC.STR("Ask again"),
        ["turn.undoTitle"] = LOC.STR("Revert every document change this turn made"),
        ["turn.undo"] = LOC.STR("Revert"),
        ["turn.stopped"] = LOC.STR("stopped"),
        ["transcript.newOutput"] = LOC.STR("New output"),
        ["chip.removeNamed"] = LOC.STR("Remove {0}"),
        ["chip.revealNamed"] = LOC.STR("Show {0} in Rhino"),

        ["tool.copyNamedSection"] = LOC.STR("Copy {0}"),
        ["tool.arguments"] = LOC.STR("arguments"),
        ["tool.result"] = LOC.STR("result"),
        ["tool.noResult"] = LOC.STR("No result reported, so this may or may not have run."),

        ["preview.captured"] = LOC.STR("Captured viewport"),
        ["preview.revealObject"] = LOC.STR("Select and zoom to this object in Rhino"),
        ["preview.wireCount"] = LOC.STR("{0} wires"),
        ["preview.errorCount"] = LOC.STR("{0} errors"),
        ["preview.warningCount"] = LOC.STR("{0} warnings"),

        ["status.workingForScreenReader"] = LOC.STR("Working"),

        ["busy.mulling"] = LOC.STR("Mulling"),
        ["busy.grazing"] = LOC.STR("Grazing"),
        ["busy.ruminating"] = LOC.STR("Ruminating"),
        ["busy.chewing"] = LOC.STR("Chewing"),
        ["busy.foraging"] = LOC.STR("Foraging"),
        ["busy.rummaging"] = LOC.STR("Rummaging"),
        ["busy.scouting"] = LOC.STR("Scouting"),
        ["busy.tracking"] = LOC.STR("Tracking"),
        ["busy.ferreting"] = LOC.STR("Ferreting"),
        ["busy.nosing"] = LOC.STR("Nosing"),
        ["busy.digging"] = LOC.STR("Digging"),
        ["busy.burrowing"] = LOC.STR("Burrowing"),
        ["busy.wading"] = LOC.STR("Wading"),
        ["busy.trekking"] = LOC.STR("Trekking"),
        ["busy.roaming"] = LOC.STR("Roaming"),
        ["busy.ambling"] = LOC.STR("Ambling"),
        ["busy.plodding"] = LOC.STR("Plodding"),
        ["busy.trotting"] = LOC.STR("Trotting"),
        ["busy.galloping"] = LOC.STR("Galloping"),
        ["busy.thundering"] = LOC.STR("Thundering"),
        ["busy.herding"] = LOC.STR("Herding"),
        ["busy.gathering"] = LOC.STR("Gathering"),
        ["busy.mustering"] = LOC.STR("Mustering"),
        ["busy.corralling"] = LOC.STR("Corralling"),
        ["busy.beavering"] = LOC.STR("Beavering"),
        ["busy.honing"] = LOC.STR("Honing"),
        ["busy.whirring"] = LOC.STR("Whirring"),

        ["review.readOnlyAtTime"] = LOC.STR("Read-only · {0}"),
        ["review.backToLive"] = LOC.STR("Back to live"),
        ["review.resumeTitle"] = LOC.STR("Continue this conversation with its agent"),
        ["review.resume"] = LOC.STR("Resume"),

        ["history.title"] = LOC.STR("Conversations"),
        ["history.close"] = LOC.STR("Close"),
        ["history.search"] = LOC.STR("Search prompts, agents, models…"),
        ["history.empty"] = LOC.STR("No saved conversations yet"),
        ["history.noMatch"] = LOC.STR("Nothing matches"),
        ["history.turnCountOne"] = LOC.STR("{0} turn"),
        ["history.turnCountMany"] = LOC.STR("{0} turns"),
        ["history.tokenCount"] = LOC.STR("{0} tok"),

        ["agent.menuHead"] = LOC.STR("Agent"),
        ["agent.settings"] = LOC.STR("AI settings…"),
        ["agent.useNamed"] = LOC.STR("Use {0}"),
        ["agent.reasonDisabled"] = LOC.STR("turned off in settings"),
        ["agent.reasonMissing"] = LOC.STR("not installed"),
        ["agent.reasonSignin"] = LOC.STR("needs sign-in"),

        ["composer.placeholderIdle"] = LOC.STR("Ask, or describe what you want built.  / for commands, @ for context"),
        ["composer.placeholderBusy"] = LOC.STR("Type your next message…"),
        ["composer.ariaMessage"] = LOC.STR("Message"),
        ["composer.attachFile"] = LOC.STR("Attach a file"),
        ["composer.attachContext"] = LOC.STR("Attach document context"),
        ["composer.commands"] = LOC.STR("Commands"),
        ["composer.hintStop"] = LOC.STR("Esc to stop"),
        ["composer.hintSend"] = LOC.STR("Enter to send"),
        ["composer.stop"] = LOC.STR("Stop  (Esc)"),
        ["composer.send"] = LOC.STR("Send  (Enter)"),
        ["composer.overAttachmentLimit"] = LOC.STR("{0} is {1}, over the {2} attachment limit."),

        ["cmd.newHint"] = LOC.STR("Start a fresh conversation"),
        ["cmd.historyHint"] = LOC.STR("Browse past conversations"),
        ["cmd.agentHint"] = LOC.STR("Switch agent or model"),
        ["cmd.loginHint"] = LOC.STR("Sign in to the selected CLI agent"),
        ["cmd.stopHint"] = LOC.STR("Cancel the running turn"),
        ["cmd.settingsHint"] = LOC.STR("Open AI settings"),

        ["ask.dontKnow"] = LOC.STR("I don't know"),
        ["ask.back"] = LOC.STR("Back"),
        ["ask.next"] = LOC.STR("Next"),
        ["ask.answer"] = LOC.STR("Answer"),
        ["ask.answerAll"] = LOC.STR("Answer all"),
        ["ask.cancel"] = LOC.STR("Cancel"),
        ["ask.somethingElse"] = LOC.STR("Something else…"),
        ["ask.yourAnswer"] = LOC.STR("Your answer…"),
        ["ask.progress"] = LOC.STR("Question {0} of {1}"),

        ["notice.dismiss"] = LOC.STR("Dismiss"),

        ["format.justNow"] = LOC.STR("just now"),
        ["format.minutesAgo"] = LOC.STR("{0}m ago"),
        ["format.hoursAgo"] = LOC.STR("{0}h ago"),
        ["format.daysAgo"] = LOC.STR("{0}d ago"),

        ["unsupported.title"] = LOC.STR("This panel needs a newer system WebView"),
        ["unsupported.body"] = LOC.STR("The panel renders in the WebView that comes with your operating system, so updating the OS (macOS ships WebKit with Safari) is what fixes it."),
        ["unsupported.macos"] = LOC.STR("Every Apple Silicon Mac can run a recent macOS, so this usually just means pending system updates."),
        ["unsupported.classic"] = LOC.STR("The classic AI panel keeps working in the meantime."),
        ["unsupported.showAnyway"] = LOC.STR("Show it anyway"),
    };

    public static string LanguageTag() => Localization.CurrentLanguageId switch
    {
        1028 => "zh-TW",
        1029 => "cs-CZ",
        1031 => "de-DE",
        1034 => "es-ES",
        1036 => "fr-FR",
        1040 => "it-IT",
        1041 => "ja-JP",
        1042 => "ko-KR",
        1045 => "pl-PL",
        1049 => "ru-RU",
        1055 => "tr-TR",
        2052 => "zh-CN",
        2070 => "pt-PT",
        _ => "en-US",
    };
}
