<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(RhinoSrc4Dir)RhinoProjectPropertySheets/Rhino.CS.Dll.props" Condition="'$(IsInRhino)' == 'true'" />

  <PropertyGroup>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">net8.0;net48</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('Windows'))">net8.0</TargetFrameworks>
    <AssemblyName>Acp</AssemblyName>
    <RootNamespace>Acp</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="codegen/**/*.cs" />
    <Compile Include="../../../../../version.cs" Condition="'$(IsInRhino)' == 'true'">
      <Link>Properties\version.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
