using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Server;
using RhMcp.Router;
using RhMcp.Router.Tools.Generated;

RouterConfig config = RouterConfig.FromArgs(args);

// Derived from the single source <Version> in rhino/Directory.Build.props (via
// the assembly's informational version). Strip any SourceLink "+<git-hash>"
// build-metadata suffix so ServerInfo reports a clean "0.1.3". The attribute is
// always emitted for a normally-built assembly; its absence is a broken build, so
// fail fast rather than advertise a fake version.
string informationalVersion =
    Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
    ?? throw new InvalidOperationException("router assembly missing InformationalVersion; check build config");
string routerVersion = informationalVersion.Split('+')[0];

HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

// Stdio MCP servers must not log to stdout — that's the JSON-RPC channel.
// Route all logging to stderr.
builder.Logging.ClearProviders();
builder.Logging.AddConsole(o => o.LogToStandardErrorThreshold = LogLevel.Trace);

builder.Services.AddSingleton(config);
builder.Services.AddSingleton<RhinoControlClient>();
builder.Services.AddSingleton<RhinoCrashReportFinder>();
builder.Services.AddSingleton<SlotStore>();
builder.Services.AddSingleton<RhinoManager>();
builder.Services.AddSingleton<ProxyDispatcher>();
builder.Services.AddSingleton<RouterId>();
builder.Services.AddHttpClient();

// JsonSerializerOptions used by the MCP server for tool arg/return serialization.
// Source-generated RouterJsonContext is chained first so AOT publish stays clean;
// MCP layers its own context on top of whatever we pass in.
var jsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web);
jsonOptions.TypeInfoResolverChain.Insert(0, RouterJsonContext.Default);
jsonOptions.Converters.Add(new LenientStringConverter());

var mcpBuilder = builder.Services
    .AddMcpServer(o =>
    {
        o.ServerInfo = new() { Name = "rhino-mcp-router", Version = routerVersion };
    })
    .WithStdioServerTransport();

// Replaces WithToolsFromAssembly() — that path uses Assembly.GetCallingAssembly()
// which is unsupported under NativeAOT. RouterToolRegistrar is generated by
// codegen and chains WithTools<T>() per tool class.
RouterToolRegistrar.RegisterAll(mcpBuilder, jsonOptions);

// Tools other Rhino plug-ins contribute to the Rhino plug-in at run time. Codegen cannot see
// these — it scans plugin source text at build time — so we ask each running slot what it has
// instead. The SDK appends these handlers' results to the generated catalogue above rather than
// replacing it, and only routes a call here for a name that catalogue does not have.
builder.Services.AddSingleton<SlotToolClient>();
builder.Services.AddSingleton<ContributedToolCatalog>();
builder.Services.AddSingleton<ContributedTools>();

mcpBuilder
    .WithListToolsHandler((request, ct) =>
        request.Services!.GetRequiredService<ContributedTools>().ListToolsAsync(request, ct))
    .WithCallToolHandler((request, ct) =>
        request.Services!.GetRequiredService<ContributedTools>().CallToolAsync(request, ct));

// Contributed tools appear and disappear while the client is connected, so the catalogue is
// no longer static. PostConfigure runs after the SDK's own McpServerOptionsSetup, so this wins.
builder.Services.PostConfigure<McpServerOptions>(o =>
{
    o.Capabilities ??= new();
    o.Capabilities.Tools ??= new();
    o.Capabilities.Tools.ListChanged = true;
});

var host = builder.Build();

// Construct eagerly: the watcher over the announcement directory must be live before the
// client's first tools/list, not lazily on it.
host.Services.GetRequiredService<ContributedTools>();

// Adopt any user-started Rhinos that announced themselves before the router
// came up. Cheap one-shot dir scan; later scans happen on every list_slots
// and slot-less dispatch.
host.Services.GetRequiredService<RhinoManager>().ScanAnnouncements();

// Clean up child Rhinos when Claude Code closes the stdio connection.
host.Services.GetRequiredService<IHostApplicationLifetime>().ApplicationStopping.Register(() =>
{
    host.Services.GetRequiredService<RhinoManager>().CloseAll();
});

await host.RunAsync();
