using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using RhMcp.Router;
using RhMcp.Router.Resources;
using RhMcp.Router.Tools.Generated;

RouterConfig config = RouterConfig.FromArgs(args);

HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

// Stdio MCP servers must not log to stdout — that's the JSON-RPC channel.
// Route all logging to stderr.
builder.Logging.ClearProviders();
builder.Logging.AddConsole(o => o.LogToStandardErrorThreshold = LogLevel.Trace);

builder.Services.AddSingleton(config);
builder.Services.AddSingleton<RhinoLocator>();
builder.Services.AddSingleton<RhinoControlClient>();
builder.Services.AddSingleton<RhinoCrashReportFinder>();
builder.Services.AddSingleton<SlotStore>();
builder.Services.AddSingleton<RhinoManager>();
builder.Services.AddSingleton<ProxyDispatcher>();
builder.Services.AddSingleton<RouterId>();
builder.Services.AddSingleton<RouterBuiltInResources>();
builder.Services.AddSingleton<ResourceRouteCache>();
builder.Services.AddSingleton<ResourceProxy>();
builder.Services.AddHttpClient();

// JsonSerializerOptions used by the MCP server for tool arg/return serialization.
// Source-generated RouterJsonContext is chained first so AOT publish stays clean;
// MCP layers its own context on top of whatever we pass in.
var jsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web);
jsonOptions.TypeInfoResolverChain.Insert(0, RouterJsonContext.Default);

var mcpBuilder = builder.Services
    .AddMcpServer(o =>
    {
        o.ServerInfo = new() { Name = "rhino-mcp-router", Version = "0.1.0" };
    })
    .WithStdioServerTransport();

// Replaces WithToolsFromAssembly() — that path uses Assembly.GetCallingAssembly()
// which is unsupported under NativeAOT. RouterToolRegistrar is generated by
// codegen and chains WithTools<T>() per tool class.
RouterToolRegistrar.RegisterAll(mcpBuilder, jsonOptions);

// Resource handlers — router-local built-ins + fan-out across running slots.
// The SDK auto-declares ServerCapabilities.Resources once any of these is
// wired. See rhino/router/Resources/ResourceProxy.cs for the merge / route /
// fallback semantics.
mcpBuilder
    .WithListResourcesHandler((ctx, ct) =>
    {
        ResourceProxy proxy = ctx.Services!.GetRequiredService<ResourceProxy>();
        return new ValueTask<ListResourcesResult>(proxy.ListAsync(ct));
    })
    .WithReadResourceHandler((ctx, ct) =>
    {
        ResourceProxy proxy = ctx.Services!.GetRequiredService<ResourceProxy>();
        string uri = ctx.Params?.Uri ?? throw new InvalidOperationException("`uri` is required.");
        return new ValueTask<ReadResourceResult>(proxy.ReadAsync(uri, ct));
    })
    .WithListResourceTemplatesHandler((ctx, ct) =>
    {
        ResourceProxy proxy = ctx.Services!.GetRequiredService<ResourceProxy>();
        return new ValueTask<ListResourceTemplatesResult>(proxy.ListTemplatesAsync(ct));
    });

var host = builder.Build();

// Adopt any user-started Rhinos that announced themselves before the router
// came up. Cheap one-shot dir scan; later scans happen on every list_slots
// and slot-less dispatch.
host.Services.GetRequiredService<RhinoManager>().ScanAnnouncements();

// Clean up child Rhinos when Claude Code closes the stdio connection.
host.Services.GetRequiredService<IHostApplicationLifetime>().ApplicationStopping.Register(() =>
{
    host.Services.GetRequiredService<RhinoManager>().CloseAll();
});

await host.RunAsync();
